site_name: WatchCat Docs
site_description: Documentation for WatchCat - A transparent overlay window application for desktop automation
repo_url: https://github.com/cs-magic-open/watchcat
repo_name: cs-magic-open/watchcat
site_url: https://cs-magic-open.github.io/watchcat/

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: lime
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  font:
    text: Roboto Mono
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  language: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: true
      css_style:
        width: "100%"
        height: "500px"

nav:
  - 主页: index.md
  - 快速开始: getting-started.md
  - 用户指南:
      - 安装: guide/installation.md
      - 基本使用: guide/basic-usage.md
  - 开发:
      - 贡献指南: development/contributing.md
      - 开发环境搭建: development/setup.md
      - UIUX: development/uiux.md
      - 打包发布: development/distribution.md
  - 常见问题: faq.md
  - 更新日志: changelog.md
