site_name: WatchCat Docs
site_description: Documentation for WatchCat - A transparent overlay window application for desktop automation
repo_url: https://github.com/cs-magic-open/watchcat
repo_name: cs-magic-open/watchcat

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: lime
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  font:
    text: Roboto Mono
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  language: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 主页: index.md
  - 快速开始: getting-started.md
  - 用户指南:
    - 安装: guide/installation.md
    - 基本使用: guide/basic-usage.md
    - 高级功能: guide/advanced.md
  - API参考:
    - PyQt界面: api/qt-interface.md
    - 自动化功能: api/automation.md
  - 开发:
    - 贡献指南: development/contributing.md
    - 开发环境搭建: development/setup.md
  - 更新日志: changelog.md
