[tool.poetry]
name = "transparent-overlay"
version = "0.1.0"
description = "A transparent overlay window application"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
PyQt6 = "^6.4.0"
opencv-python = "^4.8.0"
numpy = "^1.26.0"
mss = "^9.0.1"
cs-magic-log = "^0.1.1"
loguru = "^0.7.3"
pyobjc-framework-cocoa = "^10.3.2"
pyobjc-framework-quartz = "^10.3.2"
pyobjc-framework-applicationservices = "^10.3.2"
pyobjc-framework-coretext = "^10.3.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-qt = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 

[tool.briefcase.app.transparent_overlay.macOS]
requires = []
info_plist = "Info.plist" 