"""
This is a setup.py script generated by py2app for macOS application packaging.
"""

from setuptools import setup

APP = ['transparent_overlay/main.py']
DATA_FILES = [
    ('', ['default_config.json'])  # 添加默认配置文件到根目录
]
OPTIONS = {
    'argv_emulation': True,
    'packages': [
        'PyQt6',
        'cv2',
        'numpy',
        'mss',
        'plyer',
        'notifypy',
        'simpleaudio',
        'pydub'
    ],
    'iconfile': 'resources/icon.icns',
    'plist': {
        'CFBundleName': 'WatchCat',
        'CFBundleDisplayName': 'WatchCat',
        'CFBundleIdentifier': 'com.cs-magic.watchcat',
        'CFBundleVersion': '0.1.0',
        'CFBundleShortVersionString': '0.1.0',
        'LSMinimumSystemVersion': '10.10',
        'NSHighResolutionCapable': True,
        'NSHumanReadableCopyright': 'Copyright 2024 CS Magic. All rights reserved.'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    name='WatchCat',
    version='0.1.0',
)
